initial			= hub ;

flat			= FLAT hub ;

hub				= coins flat, 17
				| pipe flat , 12
				| blocks flat , 20
				| enemies flat , 20
				| cannon flat , 8
				| gaps flat , 19;
		
flat 			= FLAT flat, 5
				| FLAT hub , 95;

coins 			= COINS , 80
				| COINS coins , 20;

pipe 			= PIPE 
				| PIPEPIRANHA ;
		
blocks			= singleblock , 20
				| singleblock blocks , 80 ;
		
singleblock		= BLOCKPOWERUP
				| BLOCKCOINS , 10
				| BLOCKEMPTY , 50 ;
		
enemies			= singlenemy , 20
				| singlenemy enemies , 80 ;
				
singlenemy		= GOOMBA , 10
				| REDTURTLE , 3
				| GREENTURTLE , 3
				| SPIKY ;
				
cannon			= CANNON ;

gaps			= GAP , 5
				| STAIRSUP GAP STAIRSDOWN ;