rulelist		=  1*( rule / (*c-wsp c-nl) )

rule			=  nonterminal *c-wsp "=" *c-wsp alternation

alternation		=  concatenation
                   *(*c-wsp "|" *c-wsp concatenation)

concatenation	=  element *(1*c-wsp element) *c-wsp "," *c-wsp weight

element			=  nonterminal / terminal

nonterminal		=  UPCASE *(UPCASE)

terminal		=  LOWCASE *(LOWCASE)

weight			=  1*(DIGIT) ["." 1*DIGIT]

c-wsp			=  WSP / (c-nl WSP)

c-nl			=  comment / CRLF

comment			=  ";" *(WSP / VCHAR) CRLF

UPCASE			=  %x41-5A		; A-Z
 
LOWCASE			=  %x61-7A		; a-z
 
DIGIT			=  %x30-39		; 0-9
                        
VCHAR			=  %x21-7E		; visible (printing) characters

CRLF			=  %x0D %x0A	; CR LF

WSP				=  %x20 / %x09	; space or tab